### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by cruduxcru0** [cruduxcru0/WTFfw#1]
- [ ] ZIP/RAR/7z reading
- [ ] Deflate/LZMA/LZ4 compression
- [ ] CHD/BIN+CUE+MP3/FLAC/Vorbis/ISO etc reading
- [ ] MIDI synthesis
- [ ] Write self contained WASAPI audio playback
